package com.example.xiaojun.linghejiedao.beans;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xiaojun.linghejiedao.beans.MoShengRenBean;
import com.example.xiaojun.linghejiedao.beans.ShiPingBean;

import com.example.xiaojun.linghejiedao.beans.MoShengRenBeanDao;
import com.example.xiaojun.linghejiedao.beans.ShiPingBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig moShengRenBeanDaoConfig;
    private final DaoConfig shiPingBeanDaoConfig;

    private final MoShengRenBeanDao moShengRenBeanDao;
    private final ShiPingBeanDao shiPingBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        moShengRenBeanDaoConfig = daoConfigMap.get(MoShengRenBeanDao.class).clone();
        moShengRenBeanDaoConfig.initIdentityScope(type);

        shiPingBeanDaoConfig = daoConfigMap.get(ShiPingBeanDao.class).clone();
        shiPingBeanDaoConfig.initIdentityScope(type);

        moShengRenBeanDao = new MoShengRenBeanDao(moShengRenBeanDaoConfig, this);
        shiPingBeanDao = new ShiPingBeanDao(shiPingBeanDaoConfig, this);

        registerDao(MoShengRenBean.class, moShengRenBeanDao);
        registerDao(ShiPingBean.class, shiPingBeanDao);
    }
    
    public void clear() {
        moShengRenBeanDaoConfig.clearIdentityScope();
        shiPingBeanDaoConfig.clearIdentityScope();
    }

    public MoShengRenBeanDao getMoShengRenBeanDao() {
        return moShengRenBeanDao;
    }

    public ShiPingBeanDao getShiPingBeanDao() {
        return shiPingBeanDao;
    }

}
